//! Install the host-tier observability stack onto the hypervisors (ADR-098).
//!
//! Ported from `deploy-observability.py`.
//!
//! WHY THE HOST AND NOT THE CLUSTER: the metrics store must survive a cluster
//! rebuild and be able to WATCH one happen. Something inside that cluster can
//! do neither.
//!
//! WHY BINARIES ARE FETCHED ON THE HOST RATHER THAN PUSHED: pinned by version
//! AND verified by sha256 from versions.yml, so a rebuild months from now
//! installs the same bytes — the checksum guarantees that, not the tag.
//!
//! WHY ONE PRIVILEGED INSTALLER (ADR-078): staging happens as the ordinary
//! user; exactly one `sudo` runs the installer.

pub mod alerts;

use crate::config::SiteConfig;
use crate::exec::{Host, run, shell_quote};
use crate::updates::{self, PlannedFile};
use anyhow::{Context, Result, bail};
use serde_yaml_ng::Value;
use std::path::Path;

/// The docker bridge gateway. Grafana binds this and nothing else, so it is
/// unreachable from the LAN except through the edge.
pub const GRAFANA_BIND: &str = "172.18.0.1";

const INSTALLER: &str = include_str!("installer.sh.tmpl");

fn addr_of(target: &str) -> &str {
    target.rsplit_once('@').map_or(target, |(_, a)| a)
}

/// Every hypervisor's address as its PEERS reach it — the node_exporter
/// allow-list. `peer_target` is the field that always carries a reachable
/// address; `ssh_target` is None for the local machine.
pub fn peer_addresses(cfg: &SiteConfig) -> Vec<String> {
    let mut v: Vec<String> = cfg
        .hypervisors
        .values()
        .filter_map(|hv| hv.peer_target.as_deref().or(hv.ssh_target.as_deref()))
        .map(|t| addr_of(t).to_string())
        .collect();
    v.sort();
    v.dedup();
    v
}

/// Each hypervisor as (name, address), sorted by name — a scrape target needs
/// both, so dashboards identify a host without printing where it lives.
pub fn peer_targets_by_name(cfg: &SiteConfig) -> Vec<(String, String)> {
    cfg.hypervisors
        .iter()
        .filter_map(|(n, hv)| {
            hv.peer_target
                .as_deref()
                .or(hv.ssh_target.as_deref())
                .map(|t| (n.clone(), addr_of(t).to_string()))
        })
        .collect()
}

/// Every k0s node's address: log ingest is pushed FROM the cluster, so 9428
/// admits the nodes while 9100 admits only the hypervisors that scrape it.
pub fn node_addresses(cfg: &SiteConfig) -> Vec<String> {
    let mut v: Vec<String> = cfg.nodes.values().map(|n| n.ip.clone()).collect();
    v.sort();
    v.dedup();
    v
}

/// Which components this host installs: node_exporter everywhere, the store
/// only on the nominated host.
pub fn components_for(cfg: &SiteConfig, host: &str) -> Vec<&'static str> {
    let mut which = vec!["node_exporter"];
    if cfg.observability.host.as_deref() == Some(host) {
        which.extend([
            "victoria_metrics",
            "victoria_logs",
            "grafana",
            "victoria_logs_datasource",
        ]);
    }
    which
}

fn host_address(cfg: &SiteConfig, host: &str) -> String {
    cfg.hypervisors
        .get(host)
        .and_then(|hv| hv.peer_target.as_deref().or(hv.ssh_target.as_deref()))
        .map_or(String::new(), |t| addr_of(t).to_string())
}

/// The pinned observability components from versions.yml, as raw YAML.
fn versions(repo: &Path) -> Result<Value> {
    let text =
        std::fs::read_to_string(repo.join("versions.yml")).context("reading versions.yml")?;
    let v: Value = serde_yaml_ng::from_str(&text)?;
    v.get("observability")
        .cloned()
        .context("versions.yml: missing observability")
}

fn vstr<'a>(spec: &'a Value, key: &str) -> Result<&'a str> {
    spec.get(key)
        .and_then(Value::as_str)
        .with_context(|| format!("versions.yml: observability component missing `{key}`"))
}

/// VictoriaMetrics' own scrape config: the hypervisors directly, plus the
/// stack scraping ITSELF. Cluster metrics arrive by remote_write from the
/// in-cluster vmagent — a host scraper cannot reach pod IPs.
pub fn scrape_config(cfg: &SiteConfig) -> String {
    let blocks = peer_targets_by_name(cfg)
        .iter()
        .map(|(name, address)| {
            format!(
                "      - targets: [{address}:9100]
        labels:
          tier: hypervisor
          host: {name}"
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    let store = cfg.observability.host.as_deref().unwrap_or("");
    format!(
        "# Generated by deploy-observability.py — do not edit by hand.
#
# The hypervisors, plus this host's own observability stack. Cluster metrics
# arrive by remote_write from the in-cluster vmagent, because a scraper on the
# host cannot reach pod IPs.
global:
  scrape_interval: 30s

scrape_configs:
  - job_name: hypervisors
    static_configs:
{blocks}

  # A monitoring system that does not monitor itself fails silently by
  # construction: the component that would have reported the fault is the one
  # that is broken.
  - job_name: observability
    static_configs:
      - targets: [127.0.0.1:8428]
        labels:
          tier: observability
          component: victoria-metrics
          host: {store}
      - targets: [127.0.0.1:9428]
        labels:
          tier: observability
          component: victoria-logs
          host: {store}
      - targets: [{GRAFANA_BIND}:3000]
        labels:
          tier: observability
          component: grafana
          host: {store}
"
    )
}

/// grafana.ini from the template and site.yml. REFUSES GitHub auth without
/// an organisation: Grafana's default with `enabled = true` and no
/// `allowed_organizations` is not "nobody" — it is EVERYBODY with a GitHub
/// account, and it fails open.
pub fn grafana_ini(repo: &Path, cfg: &SiteConfig) -> Result<String> {
    let org = cfg.observability.github_org.as_deref().unwrap_or("").trim();
    let hostname = cfg.observability.hostname.as_deref().unwrap_or("").trim();
    if hostname.is_empty() {
        bail!(
            "site.yml: observability.hostname is required — Grafana needs it for root_url, and without it login fails in a way that looks like a proxy fault."
        );
    }
    let template = std::fs::read_to_string(repo.join("observability-host/grafana.ini.template"))?;
    Ok(template
        .replace("__HOSTNAME__", hostname)
        .replace(
            "__GITHUB_ENABLED__",
            if org.is_empty() { "false" } else { "true" },
        )
        .replace("__GITHUB_ORG__", if org.is_empty() { "!none" } else { org }))
}

/// The edge route for Grafana. Kept here so the route and the service it
/// points at are one decision.
pub fn traefik_route(repo: &Path, cfg: &SiteConfig) -> Result<String> {
    let template =
        std::fs::read_to_string(repo.join("observability-host/traefik/observe.yml.template"))?;
    Ok(template
        .replace(
            "__HOSTNAME__",
            cfg.observability.hostname.as_deref().unwrap_or(""),
        )
        .replace("__GRAFANA_ADDR__", GRAFANA_BIND))
}

fn pf(data: impl Into<Vec<u8>>, remote: &str, mode: u32) -> PlannedFile {
    PlannedFile {
        data: data.into(),
        remote: remote.to_string(),
        mode,
        owner: None,
    }
}

/// The (bytes, path, mode) set this host receives.
pub fn files_for(
    repo: &Path,
    cfg: &SiteConfig,
    host: &str,
    topic: Option<&str>,
) -> Result<Vec<PlannedFile>> {
    let unit = |name: &str| -> Result<Vec<u8>> {
        std::fs::read(repo.join("systemd/observability").join(name))
            .with_context(|| format!("reading systemd/observability/{name}"))
    };
    let file = |p: &str| -> Result<Vec<u8>> {
        std::fs::read(repo.join(p)).with_context(|| format!("reading {p}"))
    };
    let mut payload = vec![
        pf(
            unit("node-exporter.service")?,
            "etc/systemd/system/node-exporter.service",
            0o644,
        ),
        pf(
            unit("observability-notify@.service")?,
            "etc/systemd/system/observability-notify@.service",
            0o644,
        ),
        pf(
            unit("substrate-reconcile.service")?,
            "etc/systemd/system/substrate-reconcile.service",
            0o644,
        ),
        pf(
            unit("substrate-reconcile.timer")?,
            "etc/systemd/system/substrate-reconcile.timer",
            0o644,
        ),
        pf(
            file("substrate-reconcile.sh")?,
            "usr/local/bin/substrate-reconcile.sh",
            0o755,
        ),
    ];
    if components_for(cfg, host).contains(&"victoria_metrics") {
        payload.push(pf(
            unit("victoria-metrics.service")?,
            "etc/systemd/system/victoria-metrics.service",
            0o644,
        ));
        payload.push(pf(
            unit("victoria-logs.service")?,
            "etc/systemd/system/victoria-logs.service",
            0o644,
        ));
        payload.push(pf(
            scrape_config(cfg),
            "etc/victoria-metrics/scrape.yml",
            0o644,
        ));
        payload.push(pf(
            grafana_ini(repo, cfg)?,
            "etc/grafana/grafana.ini",
            0o644,
        ));
        payload.push(pf(
            file("observability-host/provisioning/datasources/victoria.yaml")?,
            "etc/grafana/provisioning/datasources/victoria.yaml",
            0o644,
        ));
        payload.push(pf(
            file("observability-host/provisioning/dashboards/repository.yaml")?,
            "etc/grafana/provisioning/dashboards/repository.yaml",
            0o644,
        ));
        payload.push(pf(
            alerts::alert_rules(),
            "etc/grafana/provisioning/alerting/rules.yaml",
            0o644,
        ));
        if let Some(t) = topic {
            // CONTAINS A CREDENTIAL (the ntfy topic): root:grafana 0640.
            payload.push(pf(
                alerts::contact_points(t),
                "etc/grafana/provisioning/alerting/contactpoints.yaml",
                0o640,
            ));
        }
        let mut boards: Vec<_> = std::fs::read_dir(repo.join("observability-host/dashboards"))?
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.extension().is_some_and(|x| x == "json"))
            .collect();
        boards.sort();
        for board in boards {
            let name = board.file_name().unwrap().to_string_lossy().into_owned();
            payload.push(pf(
                std::fs::read(&board)?,
                &format!("var/lib/grafana/dashboards/{name}"),
                0o644,
            ));
        }
        payload.push(pf(
            unit("grafana.service")?,
            "etc/systemd/system/grafana.service",
            0o644,
        ));
        payload.push(pf(
            unit("grafana-health.service")?,
            "etc/systemd/system/grafana-health.service",
            0o644,
        ));
        payload.push(pf(
            unit("grafana-health.timer")?,
            "etc/systemd/system/grafana-health.timer",
            0o644,
        ));
        payload.push(pf(
            file("grafana-health.sh")?,
            "usr/local/bin/grafana-health.sh",
            0o755,
        ));
    }
    Ok(payload)
}

/// The systemd unit basenames this host receives — derived from the payload
/// it is actually sent, never a second hand-maintained list.
pub fn unit_files_for(files: &[PlannedFile]) -> Vec<String> {
    let mut v: Vec<String> = files
        .iter()
        .filter(|f| f.remote.ends_with(".service") || f.remote.ends_with(".timer"))
        .map(|f| f.remote.rsplit('/').next().unwrap_or("").to_string())
        .collect();
    v.sort();
    v
}

/// Substitute the per-host decisions into the installer. Rendered per host
/// rather than branched inside bash: which components a host installs is a
/// decision made from typed config.
pub fn render_installer(
    repo: &Path,
    cfg: &SiteConfig,
    host: &str,
    files: &[PlannedFile],
) -> Result<String> {
    let versions = versions(repo)?;
    let mut calls = Vec::new();
    for name in components_for(cfg, host) {
        let spec = versions
            .get(name)
            .with_context(|| format!("versions.yml: observability.{name} missing"))?;
        let version = vstr(spec, "version")?;
        let url = vstr(spec, "url")?.replace("{version}", version);
        let sha = vstr(spec, "sha256")?;
        let (verb, a, b) = if spec.get("plugin_root").is_some() {
            (
                "install_plugin",
                vstr(spec, "plugin_root")?,
                vstr(spec, "install_to")?,
            )
        } else if spec.get("tree_root").is_some() {
            (
                "install_tree",
                vstr(spec, "tree_root")?,
                vstr(spec, "install_to")?,
            )
        } else {
            (
                "install_binary",
                vstr(spec, "member")?,
                vstr(spec, "install_as")?,
            )
        };
        let fields = [name, version, &url, sha, a, b];
        calls.push(format!(
            "{verb} {}",
            fields
                .iter()
                .map(|f| shell_quote(f))
                .collect::<Vec<_>>()
                .join(" ")
        ));
    }
    let wants_store = components_for(cfg, host).contains(&"victoria_metrics");
    Ok(INSTALLER
        .replace("__INSTALL_CALLS__", &calls.join("\n"))
        .replace("__WANTS_STORE__", if wants_store { "true" } else { "false" })
        .replace("__SCRAPERS__", &peer_addresses(cfg).join(" "))
        .replace("__CLUSTER_NODES__", &node_addresses(cfg).join(" "))
        .replace("__UNIT_FILES__", &unit_files_for(files).join(" "))
        .replace("__HOST_ADDR__", &host_address(cfg, host))
        .replace(
            "__ENABLE_STORE__",
            if wants_store {
                "systemctl enable --now victoria-metrics.service victoria-logs.service grafana.service grafana-health.timer >/dev/null"
            } else {
                ""
            },
        )
        .replace(
            "__VERIFY_STORE__",
            if wants_store {
                "echo \"  victoria-metrics: $(systemctl is-active victoria-metrics.service)\"\n\
                 echo \"  victoria-logs:    $(systemctl is-active victoria-logs.service)\"\n\
                 if [ ! -e /etc/grafana/grafana.env ]; then\n\
                 \x20 echo \"  grafana:          NOT CONFIGURED — /etc/grafana/grafana.env is missing (GitHub OAuth secret)\"\n\
                 else\n\
                 \x20 echo \"  grafana:          $(systemctl is-active grafana.service)\"\n\
                 fi"
            } else {
                ""
            },
        ))
}

fn sha256_hex(data: &[u8]) -> String {
    use sha2::Digest as _;
    let d = sha2::Sha256::digest(data);
    d.iter().map(|b| format!("{b:02x}")).collect()
}

/// The offline drift check's entire input: `sha256sum -c` lines plus each
/// pinned version as a comment. Written at deploy time so the checker never
/// needs git — a root timer that pulls and executes makes push access to the
/// repository root on the hypervisor (ADR-101).
pub fn manifest_for(
    repo: &Path,
    cfg: &SiteConfig,
    host: &str,
    payload: &[PlannedFile],
) -> Result<String> {
    let versions = versions(repo)?;
    let mut lines = vec![
        "# Written by deploy-observability.py. Input to substrate-reconcile.sh.".to_string(),
        "# `# pinned:` lines are read by that script; sha256sum ignores them.".to_string(),
    ];
    for name in components_for(cfg, host) {
        let v = versions
            .get(name)
            .and_then(|s| s.get("version"))
            .and_then(Value::as_str)
            .unwrap_or("");
        lines.push(format!("# pinned: {name}={v}"));
    }
    for f in payload {
        lines.push(format!("{}  /{}", sha256_hex(&f.data), f.remote));
    }
    Ok(lines.join("\n") + "\n")
}

/// Drift between the repository and what a host has installed. The host tier
/// has no reconciler; this cannot fix drift, but it refuses to let it be
/// invisible (ADR-100). Returns (problems, unverified).
pub fn check(
    repo: &Path,
    cfg: &SiteConfig,
    host: &Host,
    topic: Option<&str>,
) -> Result<(Vec<String>, Vec<String>)> {
    let mut problems = Vec::new();
    let mut unverified = Vec::new();
    for f in files_for(repo, cfg, &host.name, topic)? {
        let want = sha256_hex(&f.data);
        let path = format!("/{}", f.remote);
        let out = run(
            host,
            &[
                "sh",
                "-c",
                "if [ ! -e \"$1\" ]; then echo __ABSENT__; elif [ ! -r \"$1\" ]; then echo __UNREADABLE__; else sha256sum \"$1\"; fi",
                "_",
                &path,
            ],
            None,
        )?;
        let got = out.stdout.trim().to_string();
        if !out.ok() || got == "__ABSENT__" {
            problems.push(format!("{}: {path} is MISSING", host.name));
            continue;
        }
        if got == "__UNREADABLE__" {
            unverified.push(format!(
                "{}: {path} could not be read (permission denied) — re-run as root to verify it",
                host.name
            ));
            continue;
        }
        if got.split_whitespace().next() != Some(want.as_str()) {
            problems.push(format!("{}: {path} differs from the repository", host.name));
        }
    }
    let versions = versions(repo)?;
    for name in components_for(cfg, &host.name) {
        let want = versions
            .get(name)
            .and_then(|s| s.get("version"))
            .and_then(Value::as_str)
            .unwrap_or("");
        let out = run(
            host,
            &[
                "cat",
                &format!("/usr/local/lib/substrate-observability/{name}"),
            ],
            None,
        )?;
        let got = if out.ok() {
            out.stdout.trim().to_string()
        } else {
            "(absent)".to_string()
        };
        if got != want {
            problems.push(format!(
                "{}: {name} is {got}, repository pins {want}",
                host.name
            ));
        }
    }
    Ok((problems, unverified))
}

/// Stage this host's payload, then run its installer under one sudo — or,
/// with `dry_run`, print the plan and the installer itself.
pub fn deploy(
    repo: &Path,
    cfg: &SiteConfig,
    host: &Host,
    topic: Option<&str>,
    dry_run: bool,
) -> Result<()> {
    println!(
        "=== {}: {}",
        host.name,
        components_for(cfg, &host.name).join(", ")
    );
    if topic.is_none() && cfg.observability.host.as_deref() == Some(host.name.as_str()) {
        println!(
            "[{}] WARNING: no NTFY_TOPIC (env or ~/homelab/.env).",
            host.name
        );
        println!(
            "[{}]          alert rules will be provisioned but will",
            host.name
        );
        println!(
            "[{}]          have NOWHERE TO SEND. Alerts will not page.",
            host.name
        );
    }
    let mut files = files_for(repo, cfg, &host.name, topic)?;
    let installer = render_installer(repo, cfg, &host.name, &files)?;
    let manifest = manifest_for(repo, cfg, &host.name, &files)?;
    files.push(pf(manifest, "etc/substrate/observability.manifest", 0o644));
    if dry_run {
        for f in &files {
            println!("    would install /{} ({:o})", f.remote, f.mode);
        }
        println!("    --- installer ---");
        for line in installer.lines() {
            println!("    {line}");
        }
        return Ok(());
    }
    let staging = {
        let out = run(
            host,
            &["mktemp", "-d", "/tmp/substrate-observability.XXXXXX"],
            None,
        )?;
        out.stdout.trim().to_string()
    };
    if staging.is_empty() {
        bail!("[{}] could not create a staging directory", host.name);
    }
    let result = (|| -> Result<()> {
        run(host, &["chmod", "700", &staging], None)?;
        let stamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_secs();
        updates::stage_bytes_pub(
            host,
            &updates::build_payload(&files, stamp)?,
            &format!("{staging}/payload.tar.gz"),
        )?;
        updates::stage_bytes_pub(host, installer.as_bytes(), &format!("{staging}/install.sh"))?;
        let inner = format!("sudo bash {}/install.sh", shell_quote(&staging));
        let status = match &host.ssh_target {
            None => std::process::Command::new("bash")
                .args(["-c", &inner])
                .status()?,
            Some(t) => std::process::Command::new("ssh")
                .args(["-t", t, &inner])
                .status()?,
        };
        if !status.success() {
            bail!("[{}] installer failed", host.name);
        }
        Ok(())
    })();
    let _ = run(host, &["rm", "-rf", &staging], None);
    result
}
