#!/usr/bin/env python3
"""
Deploy the nightly-update machinery to every hypervisor.

Idempotent — safe to re-run; it overwrites the scripts/units and re-enables the
timer each time, which is what you want when the repo is the source of truth.

Installs per host:
  /usr/local/bin/hypervisor-update.sh     nightly updates + gated reboot
  /usr/local/bin/hypervisor-uncordon.sh   un-cordon nodes after a reboot
  /usr/local/bin/homelab-notify.sh        ntfy push notifier used by OnFailure=
  /etc/homelab/update.env                 PEER_HOST + KUBECONFIG_PATH
  /etc/homelab/notify.env                 NTFY_TOPIC (0600, root-only)
  /etc/homelab/kubeconfig                 cluster access for the health gate
  systemd: hypervisor-update.{service,timer}, hypervisor-uncordon.service,
           hypervisor-update-notify.service
  kubectl (from the upstream k8s release, needed by both scripts)

NTFY_TOPIC is read from the environment, falling back to ~/homelab/.env on the
machine you run this from. It is never stored in this repo. Without it the
notifier is still installed but will refuse to send, and the deploy says so.

All privileged work on a host happens in ONE `sudo` invocation. The previous
design made ~15 separate `sudo` calls over SSH, which cannot authenticate on a
host that requires a password: sudo 1.9 keys its timestamp to the tty, and every
`ssh` gets a fresh pty, so each call would prompt independently and a BatchMode
connection could not prompt at all. Only the local host worked, and only because
it inherited the caller's tty. Now the files are staged unprivileged into a 0700
temp dir and a single installer script is run under one `sudo` — so a password
is asked for at most once per host, and no NOPASSWD rule is needed anywhere.

Run from server1, from an interactive terminal (sudo may prompt):
    python3 deploy_updates.py
Do NOT run it under `sudo`: as root it would SSH as root, which has no key.
"""

from __future__ import annotations

import argparse

import io
import shlex
import subprocess
import sys
import tarfile
import time
from pathlib import Path

import siteconfig
from hosts import HOSTS, Host, ADMIN_USER

REPO = Path(__file__).resolve().parent
KUBECTL_URL = "https://dl.k8s.io/release/v1.36.1/bin/linux/amd64/kubectl"


def run(host: Host, argv: list[str], check: bool = True, input_text: str | None = None):
    """Run an UNPRIVILEGED command on the host and capture its output.

    Never use this for anything needing sudo — that is what apply() is for.
    """
    if host.ssh_target is None:
        cmd = argv
    else:
        cmd = ["ssh", "-o", "BatchMode=yes", host.ssh_target, shlex.join(argv)]
    result = subprocess.run(
        cmd, capture_output=True, text=True, input=input_text, check=False
    )
    if check and result.returncode != 0:
        raise RuntimeError(f"[{host.name}] {argv} failed:\n{result.stderr}")
    return result


def stage_bytes(host: Host, data: bytes, remote: str) -> None:
    """Write bytes to an unprivileged path on the host.

    Deliberately NOT privileged: staging happens as the ordinary user so that
    the single sudo can be spent on the installer alone (ADR-078)."""
    if host.ssh_target is None:
        Path(remote).write_bytes(data)
        return
    cmd = [
        "ssh",
        "-o",
        "BatchMode=yes",
        host.ssh_target,
        f"cat > {shlex.quote(remote)}",
    ]
    result = subprocess.run(cmd, input=data, capture_output=True, check=False)
    if result.returncode != 0:
        raise RuntimeError(
            f"[{host.name}] staging {remote} failed:\n{result.stderr.decode(errors='replace')}"
        )


def build_payload(files: list[tuple[bytes, str, int]]) -> bytes:
    """Tar the install set, with every entry owned by root and mode-pinned.

    Modes travel in the archive rather than being chmod'd afterwards, so the
    secret files are never briefly world-readable at their destination.

    mtime is stamped with the deploy time, not left at TarInfo's default of 0 —
    that default landed every deployed file dated 1969, which silently defeats
    `ls -lt`, `find -newer`, incremental backups, and any "what changed on this
    host recently" question. Deploy time is also the more useful answer than the
    repo file's mtime: it dates the event, and generated files like update.env
    have no source mtime at all.
    """
    stamp = int(time.time())
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as tf:
        for data, arcname, mode in files:
            info = tarfile.TarInfo(arcname)
            info.size = len(data)
            info.mode = mode
            info.mtime = stamp
            info.uid = info.gid = 0
            info.uname = info.gname = "root"
            tf.addfile(info, io.BytesIO(data))
    return buf.getvalue()


INSTALLER = """#!/bin/bash
# Generated by deploy_updates.py. Everything privileged happens here, once.
set -euo pipefail
umask 022
HERE="$(cd "$(dirname "$0")" && pwd)"

install -d -m 0755 /etc/homelab
tar -xzpf "$HERE/payload.tar.gz" -C /

if ! command -v kubectl >/dev/null 2>&1; then
    echo "  installing kubectl..."
    curl -fsSL -o /usr/local/bin/kubectl "__KUBECTL_URL__"
    chmod 0755 /usr/local/bin/kubectl
else
    echo "  kubectl already present"
fi

systemctl daemon-reload
systemctl enable --now hypervisor-update.timer >/dev/null
systemctl enable hypervisor-uncordon.service >/dev/null

echo "  update.timer:    $(systemctl is-enabled hypervisor-update.timer)"
echo "  uncordon:        $(systemctl is-enabled hypervisor-uncordon.service)"
echo "  OnFailure:       $(systemctl show -p OnFailure --value hypervisor-update.service)"
echo "  notify.env:      $(stat -c '%a %U' /etc/homelab/notify.env 2>/dev/null || echo 'ABSENT - failures will not notify')"
echo "  kubeconfig:      $(stat -c '%a %U' /etc/homelab/kubeconfig)"
"""


def apply(host: Host, files: list[tuple[bytes, str, int]]) -> None:
    """Stage the payload unprivileged, then run ONE privileged installer.

    The sudo step is deliberately not output-captured: a captured prompt is an
    invisible prompt, and the run would look like a hang.
    """
    staging = run(host, ["mktemp", "-d", "/tmp/substrate-deploy.XXXXXX"]).stdout.strip()
    if not staging:
        raise RuntimeError(f"[{host.name}] could not create a staging directory")
    try:
        run(host, ["chmod", "700", staging])
        stage_bytes(host, build_payload(files), f"{staging}/payload.tar.gz")
        stage_bytes(
            host,
            INSTALLER.replace("__KUBECTL_URL__", KUBECTL_URL).encode(),
            f"{staging}/install.sh",
        )
        run(host, ["chmod", "600", f"{staging}/payload.tar.gz"])

        inner = f"sudo bash {shlex.quote(staging)}/install.sh"
        if host.ssh_target is None:
            cmd = ["bash", "-c", inner]
        else:
            # -t so sudo can prompt on a real pty; no BatchMode, for the same reason.
            cmd = ["ssh", "-t", host.ssh_target, inner]
        if subprocess.run(cmd, check=False).returncode != 0:
            raise RuntimeError(f"[{host.name}] installer failed")
    finally:
        run(host, ["rm", "-rf", staging], check=False)


def peer_of(host: Host) -> Host | None:
    """The other hypervisor, or None on a single-host fleet.

    None is handled by the caller as "skip": the nightly reboot gate needs a
    peer to ask, and installing a gate that can never find one would produce a
    check that always passes."""
    others = [h for h in HOSTS if h.name != host.name]
    return others[0] if others else None


def peer_ssh_target(host: Host, peer: Host) -> str:
    """SSH target string the HOST will use to reach its PEER.

    Note this can't just be peer.ssh_target: that's written from server1's
    point of view, and is None for server1 itself (meaning "local"). From
    another host, server1 is a real remote.
    """
    if peer.ssh_target is not None:
        return peer.ssh_target
    if peer.peer_target:
        return peer.peer_target
    raise RuntimeError(
        f"{peer.name} runs locally (ssh_target: null) and has no `peer_target` "
        f"in site.yml, so {host.name} has no way to reach it"
    )


def bootstrap_ip() -> str:
    """Address of the bootstrap controller.

    That node is where the admin kubeconfig comes from, since the cluster has
    no other management path."""
    for h in HOSTS:
        for vm in h.vms:
            if vm.bootstrap:
                return vm.static_ip
    raise RuntimeError("no bootstrap VM defined in hosts.py")


def fetch_kubeconfig() -> str:
    """Fetch the admin kubeconfig from the bootstrap node.

    Refuses output that does not look like a kubeconfig: a zero exit with junk on
    stdout would otherwise be written to both hypervisors and fail the nightly
    health gate with something unrelated-looking."""
    ip = bootstrap_ip()
    result = subprocess.run(
        [
            "ssh",
            "-o",
            "BatchMode=yes",
            "-o",
            "ConnectTimeout=10",
            "-o",
            "StrictHostKeyChecking=no",
            "-o",
            "UserKnownHostsFile=/dev/null",
            f"{ADMIN_USER}@{ip}",
            "sudo k0s kubeconfig admin",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0 or "server:" not in result.stdout:
        raise RuntimeError(f"could not fetch kubeconfig from {ip}: {result.stderr}")
    return result.stdout


def ntfy_topic() -> str | None:
    """Resolve NTFY_TOPIC from the environment, else from ~/homelab/.env.

    Deliberately not stored in this repo: an ntfy topic is a capability URL, so
    anyone holding it can publish to it.
    """
    import os

    topic = os.environ.get("NTFY_TOPIC")
    if topic:
        return topic.strip()

    env_file = Path.home() / "homelab" / ".env"
    if env_file.is_file():
        for line in env_file.read_text().splitlines():
            key, sep, value = line.partition("=")
            if sep and key.strip() == "NTFY_TOPIC":
                return value.strip().strip("'\"") or None
    return None


def deploy(host: Host, kubeconfig: str, dry_run: bool = False) -> None:
    """Install the nightly-update machinery on one hypervisor.

    Builds the complete file plan first, then hands it to apply() so every
    privileged action happens in a single sudo."""
    peer = peer_of(host)
    if peer is None:
        print(
            f"[{host.name}] SKIP: no peer hypervisor — the reboot safety gate needs one"
        )
        return

    print(f"=== {host.name} (peer: {peer.name}) ===")

    env = (
        f"PEER_HOST={peer_ssh_target(host, peer)}\n"
        f"KUBECONFIG_PATH=/etc/homelab/kubeconfig\n"
        # hypervisor-update.sh runs as root under systemd, and root has no SSH
        # key — deliberately. Peer health checks are read-only, so they run as
        # the unprivileged admin user who does have one. The script guards this
        # with ${SSH_USER:?}, so omitting it aborts the nightly update outright:
        # both hypervisors failed at 03:30 on 2026-08-29 with
        #   "SSH_USER must be set — the unprivileged account used for peer
        #    health checks"
        # after this deploy shipped a newer hypervisor-update.sh than the
        # update.env writer knew about. tests/test_deploy_env.py now asserts
        # every ${VAR:?} the shipped scripts require is written here.
        f"SSH_USER={ADMIN_USER}\n"
    )

    files: list[tuple[bytes, str, int]] = [
        (
            (REPO / "hypervisor-update.sh").read_bytes(),
            "usr/local/bin/hypervisor-update.sh",
            0o755,
        ),
        (
            (REPO / "hypervisor-uncordon.sh").read_bytes(),
            "usr/local/bin/hypervisor-uncordon.sh",
            0o755,
        ),
        ((REPO / "notify.sh").read_bytes(), "usr/local/bin/homelab-notify.sh", 0o755),
        # Cluster credentials for the health gate. Root-only: it's cluster-admin.
        (kubeconfig.encode(), "etc/homelab/kubeconfig", 0o600),
        (env.encode(), "etc/homelab/update.env", 0o644),
    ]

    for unit in (
        "hypervisor-update.service",
        "hypervisor-update.timer",
        "hypervisor-uncordon.service",
        "hypervisor-update-notify.service",
    ):
        files.append(
            (
                (REPO / "systemd" / unit).read_bytes(),
                f"etc/systemd/system/{unit}",
                0o644,
            )
        )

    # 0600 and separate from update.env: that file is world-readable and holds
    # nothing sensitive, while the ntfy topic is a publish capability.
    topic = ntfy_topic()
    if topic:
        files.append(
            (f"NTFY_TOPIC={topic}\n".encode(), "etc/homelab/notify.env", 0o600)
        )
    else:
        print(f"[{host.name}] WARNING: no NTFY_TOPIC found (env or ~/homelab/.env).")
        print(f"[{host.name}]          hypervisor-update failures will NOT notify.")

    if dry_run:
        # The file PLAN is the whole of what this does — apply() only unpacks
        # it under one sudo. Printing the plan is therefore a faithful preview
        # rather than a summary of one.
        print(f"[{host.name}] DRY RUN — would install {len(files)} file(s):")
        for _data, remote, mode in files:
            print(
                f"[{host.name}]   /{remote}  ({oct(mode)[2:]:>4}, {len(_data)} bytes)"
            )
        print(f"[{host.name}] DRY RUN — would then run the installer under one sudo")
        return

    apply(host, files)
    print(f"[{host.name}] deployed")


def main(argv: list[str] | None = None) -> None:
    """Deploy to every hypervisor, fetching the kubeconfig once.

    Fetched once rather than per host so both machines get byte-identical
    credentials — two fetches could straddle a cluster change.

    ⚠️ WHY THIS PARSES ARGUMENTS AT ALL.
    It did not until 2026-09-10, and every argument — INCLUDING `--help` — was
    silently ignored and the deployment ran. `--help` is the universally safe
    "tell me what you do without doing it", and on this script, which writes to
    both hypervisors and enables timers, it was indistinguishable from running
    the thing. It stopped only because sudo happened to prompt.

    argparse also REJECTS unknown arguments, which is the half that matters
    most: a typo in a flag now fails instead of deploying.
    """
    # Explicit, NOT `__doc__.splitlines()[0]`. The `"exec" "$(...)"` shebang
    # trick at the top of these files is a run of ADJACENT STRING LITERALS,
    # which Python concatenates into the module docstring — so `__doc__` is a
    # shell fragment and `--help` advertised
    #   exec$(cd $(dirname $0); pwd)/.venv/bin/python3-u$0$@
    # on four of this repo's operational tools until 2026-09-10.
    parser = argparse.ArgumentParser(
        description="Deploy the nightly hypervisor update machinery to every hypervisor."
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the file plan for each hypervisor and change nothing",
    )
    # argv is a PARAMETER so main() can be called from a test without argparse
    # reading pytest's own command line — which is exactly what broke
    # test_main_deploys_to_every_host the moment this parser was added.
    args = parser.parse_args(argv)

    # Checked BEFORE the kubeconfig fetch, so the refusal arrives instantly
    # instead of after an SSH round trip that fails on publickey.
    siteconfig.refuse_if_root("python3 deploy_updates.py")

    kubeconfig = fetch_kubeconfig()
    for host in HOSTS:
        deploy(host, kubeconfig, dry_run=args.dry_run)


if __name__ == "__main__":
    try:
        main()
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
