//! Deploy the nightly-update machinery to every hypervisor.
//!
//! Ported from `deploy_updates.py`. Idempotent: overwrites the scripts and
//! units and re-enables the timer each time, which is what you want when the
//! repo is the source of truth.
//!
//! All privileged work on a host happens in ONE `sudo` invocation. Files are
//! staged unprivileged into a 0700 temp dir and a single installer runs under
//! one sudo — a password is asked for at most once per host, and no NOPASSWD
//! rule is needed anywhere (ADR-078). The previous design made ~15 separate
//! sudo calls over SSH, which cannot authenticate on a host that requires a
//! password.
//!
//! Do NOT run under `sudo`: as root it would SSH as root, which has no key.

use crate::config::SiteConfig;
use crate::exec::{Host, run, shell_join, shell_quote};
use crate::provision::Fleet;
use anyhow::{Context, Result, bail};
use std::path::Path;

pub const KUBECTL_URL: &str = "https://dl.k8s.io/release/v1.36.1/bin/linux/amd64/kubectl";

/// One file in the install set: (bytes, path relative to `/`, mode).
pub struct PlannedFile {
    pub data: Vec<u8>,
    pub remote: String,
    pub mode: u32,
    /// Owning user, root when None. Set for a file a service user must read
    /// but nobody else may (a 0600 site.yml for the posture check).
    pub owner: Option<String>,
}

const INSTALLER: &str = r#"#!/bin/bash
# Generated by deploy_updates.py. Everything privileged happens here, once.
set -euo pipefail
umask 022
HERE="$(cd "$(dirname "$0")" && pwd)"

install -d -m 0755 /etc/homelab
tar -xzpf "$HERE/payload.tar.gz" -C /

if ! command -v kubectl >/dev/null 2>&1; then
    echo "  installing kubectl..."
    curl -fsSL -o /usr/local/bin/kubectl "__KUBECTL_URL__"
    chmod 0755 /usr/local/bin/kubectl
else
    echo "  kubectl already present"
fi

# cosign: what install.sh verifies a substrate release with (ADR-192). Pinned
# by checksum in versions.yml; a verifier that arrives unverified is theatre.
if /usr/local/bin/cosign version 2>/dev/null | grep -q "GitVersion:.*__COSIGN_VERSION__"; then
    echo "  cosign __COSIGN_VERSION__ already present"
else
    echo "  installing cosign __COSIGN_VERSION__..."
    tmp=$(mktemp)
    curl -fsSL -o "$tmp" "__COSIGN_URL__"
    echo "__COSIGN_SHA256__  $tmp" | sha256sum -c --quiet
    install -m 0755 -o root -g root "$tmp" /usr/local/bin/cosign
    rm -f "$tmp"
fi

systemctl daemon-reload
systemctl enable --now hypervisor-update.timer >/dev/null
systemctl enable hypervisor-uncordon.service >/dev/null

echo "  update.timer:    $(systemctl is-enabled hypervisor-update.timer)"
echo "  uncordon:        $(systemctl is-enabled hypervisor-uncordon.service)"
echo "  OnFailure:       $(systemctl show -p OnFailure --value hypervisor-update.service)"
echo "  notify.env:      $(stat -c '%a %U' /etc/homelab/notify.env 2>/dev/null || echo 'ABSENT - failures will not notify')"
echo "  kubeconfig:      $(stat -c '%a %U' /etc/homelab/kubeconfig)"
echo "  cosign:          $(/usr/local/bin/cosign version 2>/dev/null | grep -oE 'GitVersion:\s*\S+' || echo 'ABSENT - install.sh cannot verify releases')"
"#;

/// The installer with every pinned host tool substituted in. Rendered from
/// the config rather than baked, so a bump in versions.yml is the whole
/// change.
pub fn installer(cfg: &SiteConfig) -> String {
    let c = &cfg.host_tools.cosign;
    INSTALLER
        .replace("__KUBECTL_URL__", KUBECTL_URL)
        .replace("__COSIGN_VERSION__", &c.version)
        .replace("__COSIGN_URL__", &c.url)
        .replace("__COSIGN_SHA256__", &c.sha256)
}

/// Tar the install set, every entry owned by root and mode-pinned. Modes
/// travel in the archive rather than being chmod'd afterwards, so the secret
/// files are never briefly world-readable. mtime is the deploy time, not 0 —
/// the default landed every deployed file dated 1969.
pub fn build_payload(files: &[PlannedFile], stamp: u64) -> Result<Vec<u8>> {
    let gz = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());
    let mut tar = tar::Builder::new(gz);
    for f in files {
        let mut h = tar::Header::new_gnu();
        h.set_size(f.data.len() as u64);
        h.set_mode(f.mode);
        h.set_mtime(stamp);
        // Ownership travels by NAME: GNU tar, extracting as root, resolves
        // uname/gname on the host, so the uid need not be known here.
        h.set_uid(0);
        h.set_gid(0);
        h.set_username(f.owner.as_deref().unwrap_or("root"))?;
        h.set_groupname(f.owner.as_deref().unwrap_or("root"))?;
        h.set_entry_type(tar::EntryType::Regular);
        tar.append_data(&mut h, &f.remote, f.data.as_slice())?;
    }
    let gz = tar.into_inner()?;
    Ok(gz.finish()?)
}

/// Write bytes to an UNPRIVILEGED path on the host, so the single sudo can be
/// spent on the installer alone.
pub fn stage_bytes_pub(host: &Host, data: &[u8], remote: &str) -> Result<()> {
    stage_bytes(host, data, remote)
}

fn stage_bytes(host: &Host, data: &[u8], remote: &str) -> Result<()> {
    use std::io::Write as _;
    match &host.ssh_target {
        None => Ok(std::fs::write(remote, data)?),
        Some(t) => {
            let mut child = std::process::Command::new("ssh")
                .args([
                    "-o",
                    "BatchMode=yes",
                    t,
                    &format!("cat > {}", shell_quote(remote)),
                ])
                .stdin(std::process::Stdio::piped())
                .stdout(std::process::Stdio::piped())
                .stderr(std::process::Stdio::piped())
                .spawn()?;
            child.stdin.take().context("no stdin")?.write_all(data)?;
            let out = child.wait_with_output()?;
            if !out.status.success() {
                bail!(
                    "[{}] staging {remote} failed:\n{}",
                    host.name,
                    String::from_utf8_lossy(&out.stderr)
                );
            }
            Ok(())
        }
    }
}

fn run_checked(host: &Host, argv: &[&str]) -> Result<String> {
    let out = run(host, argv, None)?;
    if !out.ok() {
        bail!(
            "[{}] {} failed:\n{}",
            host.name,
            shell_join(argv),
            out.stderr
        );
    }
    Ok(out.stdout)
}

/// Stage the payload unprivileged, then run ONE privileged installer. The
/// sudo step is deliberately not output-captured: a captured prompt is an
/// invisible prompt, and the run would look like a hang.
pub fn apply(host: &Host, files: &[PlannedFile], installer: &str) -> Result<()> {
    let staging = run_checked(host, &["mktemp", "-d", "/tmp/substrate-deploy.XXXXXX"])?
        .trim()
        .to_string();
    if staging.is_empty() {
        bail!("[{}] could not create a staging directory", host.name);
    }
    let result = (|| -> Result<()> {
        run_checked(host, &["chmod", "700", &staging])?;
        let stamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_secs();
        stage_bytes(
            host,
            &build_payload(files, stamp)?,
            &format!("{staging}/payload.tar.gz"),
        )?;
        stage_bytes(host, installer.as_bytes(), &format!("{staging}/install.sh"))?;
        run_checked(
            host,
            &["chmod", "600", &format!("{staging}/payload.tar.gz")],
        )?;
        let inner = format!("sudo bash {}/install.sh", shell_quote(&staging));
        let status = match &host.ssh_target {
            None => std::process::Command::new("bash")
                .args(["-c", &inner])
                .status()?,
            // -t so sudo can prompt on a real pty; no BatchMode, for the same reason.
            Some(t) => std::process::Command::new("ssh")
                .args(["-t", t, &inner])
                .status()?,
        };
        if !status.success() {
            bail!("[{}] installer failed", host.name);
        }
        Ok(())
    })();
    let _ = run(host, &["rm", "-rf", &staging], None);
    result
}

/// SSH target string the HOST will use to reach its PEER. Not just the peer's
/// `ssh_target`: that is written from server1's point of view and is None
/// for server1 itself. From another host, server1 is a real remote.
pub fn peer_ssh_target(host: &Host, peer: &Host) -> Result<String> {
    if let Some(t) = &peer.ssh_target {
        return Ok(t.clone());
    }
    if let Some(t) = &peer.peer_target {
        return Ok(t.clone());
    }
    bail!(
        "{} runs locally (ssh_target: null) and has no `peer_target` in site.yml, so {} has no way to reach it",
        peer.name,
        host.name
    )
}

/// The admin kubeconfig from the bootstrap node. Refuses output that does not
/// look like a kubeconfig: a zero exit with junk on stdout would otherwise be
/// written to both hypervisors and fail the nightly gate mysteriously.
pub fn fetch_kubeconfig(cfg: &SiteConfig) -> Result<String> {
    let fleet = Fleet::from_config(cfg);
    let ip = &fleet.find_bootstrap()?.1.static_ip;
    let out = crate::provision::node_ssh(&cfg.admin_user, ip, 10, "sudo k0s kubeconfig admin")?;
    if !out.ok() || !out.stdout.contains("server:") {
        bail!("could not fetch kubeconfig from {ip}: {}", out.stderr);
    }
    Ok(out.stdout)
}

/// NTFY_TOPIC from the environment, else `~/homelab/.env`. Never stored in
/// the repo: an ntfy topic is a capability URL.
pub fn ntfy_topic() -> Option<String> {
    if let Some(t) = std::env::var("NTFY_TOPIC")
        .ok()
        .map(|t| t.trim().to_string())
        .filter(|t| !t.is_empty())
    {
        return Some(t);
    }
    let home = std::env::var_os("HOME")?;
    let text = std::fs::read_to_string(Path::new(&home).join("homelab").join(".env")).ok()?;
    for line in text.lines() {
        if let Some((k, v)) = line.split_once('=')
            && k.trim() == "NTFY_TOPIC"
        {
            let v = v.trim().trim_matches(|c| c == '\'' || c == '"');
            return (!v.is_empty()).then(|| v.to_string());
        }
    }
    None
}

/// The complete file plan for one host. Building it first and handing it to
/// `apply` is what keeps every privileged action inside a single sudo.
pub fn plan(
    repo: &Path,
    cfg: &SiteConfig,
    host: &Host,
    peer: &Host,
    kubeconfig: &str,
    topic: Option<&str>,
) -> Result<Vec<PlannedFile>> {
    let read = |p: &str| -> Result<Vec<u8>> {
        std::fs::read(repo.join(p)).with_context(|| format!("reading {p}"))
    };
    let env = format!(
        "PEER_HOST={}\nKUBECONFIG_PATH=/etc/homelab/kubeconfig\nSSH_USER={}\n",
        peer_ssh_target(host, peer)?,
        cfg.admin_user
    );
    let mut files = vec![
        PlannedFile {
            data: read("hypervisor-update.sh")?,
            remote: "usr/local/bin/hypervisor-update.sh".into(),
            mode: 0o755,
            owner: None,
        },
        PlannedFile {
            data: read("hypervisor-uncordon.sh")?,
            remote: "usr/local/bin/hypervisor-uncordon.sh".into(),
            mode: 0o755,
            owner: None,
        },
        PlannedFile {
            data: read("notify.sh")?,
            remote: "usr/local/bin/homelab-notify.sh".into(),
            mode: 0o755,
            owner: None,
        },
        // Cluster credentials for the health gate. Root-only: it's cluster-admin.
        PlannedFile {
            data: kubeconfig.as_bytes().to_vec(),
            remote: "etc/homelab/kubeconfig".into(),
            mode: 0o600,
            owner: None,
        },
        PlannedFile {
            data: env.into_bytes(),
            remote: "etc/homelab/update.env".into(),
            mode: 0o644,
            owner: None,
        },
    ];
    for unit in [
        "hypervisor-update.service",
        "hypervisor-update.timer",
        "hypervisor-uncordon.service",
        "hypervisor-update-notify.service",
    ] {
        files.push(PlannedFile {
            data: read(&format!("systemd/{unit}"))?,
            remote: format!("etc/systemd/system/{unit}"),
            mode: 0o644,
            owner: None,
        });
    }
    // 0600 and separate from update.env: that file is world-readable and
    // holds nothing sensitive, while the ntfy topic is a publish capability.
    if let Some(t) = topic {
        files.push(PlannedFile {
            data: format!("NTFY_TOPIC={t}\n").into_bytes(),
            remote: "etc/homelab/notify.env".into(),
            mode: 0o600,
            owner: None,
        });
    }
    Ok(files)
}

/// Deploy to every hypervisor, fetching the kubeconfig ONCE so both machines
/// get byte-identical credentials — two fetches could straddle a cluster
/// change. Returns Ok(()) after printing per-host results; errors propagate.
pub fn deploy_all(repo: &Path, cfg: &SiteConfig, dry_run: bool) -> Result<()> {
    let kubeconfig = fetch_kubeconfig(cfg)?;
    let topic = ntfy_topic();
    let hosts: Vec<Host> = cfg
        .hypervisors
        .iter()
        .map(|(n, hv)| Host::from_config(n, hv))
        .collect();
    for host in &hosts {
        let Some(peer) = hosts.iter().find(|h| h.name != host.name) else {
            println!(
                "[{}] SKIP: no peer hypervisor — the reboot safety gate needs one",
                host.name
            );
            continue;
        };
        println!("=== {} (peer: {}) ===", host.name, peer.name);
        let files = plan(repo, cfg, host, peer, &kubeconfig, topic.as_deref())?;
        if topic.is_none() {
            println!(
                "[{}] WARNING: no NTFY_TOPIC found (env or ~/homelab/.env).",
                host.name
            );
            println!(
                "[{}]          hypervisor-update failures will NOT notify.",
                host.name
            );
        }
        if dry_run {
            // The file PLAN is the whole of what this does — apply only
            // unpacks it under one sudo — so printing it is a faithful preview.
            println!(
                "[{}] DRY RUN — would install {} file(s):",
                host.name,
                files.len()
            );
            for f in &files {
                println!(
                    "[{}]   /{}  ({:>4o}, {} bytes)",
                    host.name,
                    f.remote,
                    f.mode,
                    f.data.len()
                );
            }
            println!(
                "[{}] DRY RUN — would then run the installer under one sudo (cosign {} pinned by checksum)",
                host.name, cfg.host_tools.cosign.version
            );
            continue;
        }
        apply(host, &files, &installer(cfg))?;
        println!("[{}] deployed", host.name);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read as _;

    #[test]
    fn payload_entries_are_root_owned_mode_pinned_and_dated_by_the_deploy() {
        let files = vec![
            PlannedFile {
                data: b"#!/bin/sh\n".to_vec(),
                remote: "usr/local/bin/x.sh".into(),
                mode: 0o755,
                owner: None,
            },
            PlannedFile {
                data: b"NTFY_TOPIC=t\n".to_vec(),
                remote: "etc/homelab/notify.env".into(),
                mode: 0o600,
                owner: None,
            },
        ];
        let gz = build_payload(&files, 1_700_000_000).unwrap();
        let mut ar = tar::Archive::new(flate2::read::GzDecoder::new(gz.as_slice()));
        let mut seen = Vec::new();
        for e in ar.entries().unwrap() {
            let mut e = e.unwrap();
            let h = e.header();
            assert_eq!(h.uid().unwrap(), 0);
            assert_eq!(h.username().unwrap(), Some("root"));
            assert_eq!(h.mtime().unwrap(), 1_700_000_000, "not 1969");
            let mode = h.mode().unwrap();
            let path = e.path().unwrap().to_string_lossy().into_owned();
            let mut body = String::new();
            e.read_to_string(&mut body).unwrap();
            seen.push((path, mode, body));
        }
        assert_eq!(
            seen[0],
            (
                "usr/local/bin/x.sh".to_string(),
                0o755,
                "#!/bin/sh\n".to_string()
            )
        );
        assert_eq!(
            seen[1].1, 0o600,
            "the secret file's mode travels in the archive"
        );
    }
}
